# Docker Compose for local development
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Mount local data directory for database persistence
      - ./data:/app/data
      # Mount templates for hot-reload during development
      - ./cmd/web/templates:/app/web/templates:ro
    env_file:
      - .env
    environment:
      # Override for Docker networking
      DATABASE_URL: file:/app/data/gproject.db
    restart: unless-stopped
    networks:
      - gproject-network
    # Resource limits for development
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "--timeout=2", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  gproject-network:
    driver: bridge

volumes:
  gproject-data:
    driver: local