# Docker Compose for production deployment
version: '3.8'

services:
  web:
    # Use the latest image from GitHub Container Registry
    image: ghcr.io/${GITHUB_REPOSITORY:-eshamow/gproject}:latest
    ports:
      - "8080:8080"
    volumes:
      # Named volume for database persistence (not bind mount)
      - gproject-data:/app/data
      # Temporary writable directory for SQLite WAL mode
      - /tmp
    env_file:
      - .env.production
    environment:
      # Production overrides
      DATABASE_URL: file:/app/data/gproject.db
      ENVIRONMENT: production
    restart: unless-stopped
    # Security hardening
    read_only: true
    security_opt:
      - no-new-privileges:true
    mem_limit: 512m
    networks:
      - gproject-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  gproject-network:
    driver: bridge

volumes:
  gproject-data:
    driver: local
    driver_opts:
      type: none
      o: bind,uid=1001,gid=1001
      device: /var/lib/gproject/data